config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'services/update_venues', as: 'update_venues'
  get 'services/update_dates', as: 'update_dates'
  get 'services/update_partners', as: 'update_partners'
  get 'services/dates' => 'services#renderDates'
  root 'services#index'
  resources :vendor_types

  resources :photographer_dates

  resources :caterer_dates

  resources :florist_dates

  resources :vendor_dates

  resources :venue_to_vendors

  resources :service_to_vendors

  resources :vendors

  resources :services

  resources :photographers

  resources :caterers

  resources :florists

  resources :venues

end

app/models/caterer.rb
class Caterer < ActiveRecord::Base
  has_many :CatererDates, dependent: :destroy
  belongs_to :Vendor
end

app/controllers/caterers_controller.rb
class CaterersController < ApplicationController
  before_action :set_caterer, only: [:show, :edit, :update, :destroy]

  # GET /caterers
  # GET /caterers.json
  def index
    @caterers = Caterer.all
  end

  # GET /caterers/1
  # GET /caterers/1.json
  def show
  end

  # GET /caterers/new
  def new
    @caterer = Caterer.new
  end

  # GET /caterers/1/edit
  def edit
  end

  # POST /caterers
  # POST /caterers.json
  def create
    vendor_type = VendorType.find_by vendor_type: 'caterer'
    vendor = Vendor.create( vendor_type: 'caterer', vendor_type_id: vendor_type.id)
    @caterer = caterer.new(name: caterer_params[:name], vendor_id: vendor.id)

    respond_to do |format|
      if @caterer.save
        format.html { redirect_to @caterer, notice: 'Caterer was successfully created.' }
        format.json { render :show, status: :created, location: @caterer }
      else
        format.html { render :new }
        format.json { render json: @caterer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caterers/1
  # PATCH/PUT /caterers/1.json
  def update
    respond_to do |format|
      if @caterer.update(caterer_params)
        format.html { redirect_to @caterer, notice: 'Caterer was successfully updated.' }
        format.json { render :show, status: :ok, location: @caterer }
      else
        format.html { render :edit }
        format.json { render json: @caterer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caterers/1
  # DELETE /caterers/1.json
  def destroy
    @caterer.destroy
    respond_to do |format|
      format.html { redirect_to caterers_url, notice: 'Caterer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caterer
      @caterer = Caterer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caterer_params
      params.require(:caterer).permit(:name)
    end
end

app/helpers/caterers_helper.rb
module CaterersHelper
end

app/views/caterers/_caterer.html.erb
<option value="<%= caterer.id %>"><%= caterer.name.titleize %></option>

app/views/caterers/_form.html.erb
<%= form_for(@caterer) do |f| %>
  <% if @caterer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caterer.errors.count, "error") %> prohibited this caterer from being saved:</h2>

      <ul>
      <% @caterer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caterers/edit.html.erb
<h1>Editing caterer</h1>

<%= render 'form' %>

<%= link_to 'Show', @caterer %> |
<%= link_to 'Back', caterers_path %>

app/views/caterers/index.html.erb
<h1>Listing caterers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caterers.each do |caterer| %>
      <tr>
        <td><%= caterer.name %></td>
        <td><%= link_to 'Show', caterer %></td>
        <td><%= link_to 'Edit', edit_caterer_path(caterer) %></td>
        <td><%= link_to 'Destroy', caterer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caterer', new_caterer_path %>

app/views/caterers/new.html.erb
<h1>New caterer</h1>

<%= render 'form' %>

<%= link_to 'Back', caterers_path %>

app/views/caterers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @caterer.name %>
</p>

<%= link_to 'Edit', edit_caterer_path(@caterer) %> |
<%= link_to 'Back', caterers_path %>