config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'services/update_venues', as: 'update_venues'
  get 'services/update_dates', as: 'update_dates'
  get 'services/update_partners', as: 'update_partners'
  get 'services/dates' => 'services#renderDates'
  root 'services#index'
  resources :vendor_types

  resources :photographer_dates

  resources :caterer_dates

  resources :florist_dates

  resources :vendor_dates

  resources :venue_to_vendors

  resources :service_to_vendors

  resources :vendors

  resources :services

  resources :photographers

  resources :caterers

  resources :florists

  resources :venues

end

app/models/caterer.rb
class Caterer < ActiveRecord::Base
  has_many :CatererDates, dependent: :destroy
  belongs_to :Vendor
end

app/models/florist.rb
class Florist < ActiveRecord::Base
  has_many :FloristDates, dependent: :destroy
  belongs_to :Vendor
end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
  has_many :PhotographerDates, dependent: :destroy
  belongs_to :Vendor
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :VendorDates
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :ServiceToVendors, dependent: :destroy
  has_many :VenueToVendors, dependent: :destroy
  has_many :Services, :through => :ServiceToVendors
  has_many :Venues, dependent: :destroy
  has_many :Caterers, dependent: :destroy
  has_many :Florists, dependent: :destroy
  has_many :Photographers, dependent: :destroy
  belongs_to :VendorType
end

app/models/vendor_date.rb
class VendorDate < ActiveRecord::Base
  belongs_to :Vendor
  belongs_to :Service
end

app/models/vendor_type.rb
class VendorType < ActiveRecord::Base
  has_many :Vendors
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :VendorDates
  has_many :VenueToVendors, dependent: :destroy
  belongs_to :Vendor
end

app/models/venue_date.rb
class VenueDate < ActiveRecord::Base
  belongs_to :Venue
  belongs_to :Service
end

app/models/venue_to_vendor.rb
class VenueToVendor < ActiveRecord::Base
  belongs_to :Venue
  belongs_to :Vendor
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:vendor_type)
    end
end

app/controllers/venue_to_vendors_controller.rb
class VenueToVendorsController < ApplicationController
  before_action :set_venue_to_vendor, only: [:show, :edit, :update, :destroy]

  # GET /venue_to_vendors
  # GET /venue_to_vendors.json
  def index
    @venue_to_vendors = VenueToVendor.all
  end

  # GET /venue_to_vendors/1
  # GET /venue_to_vendors/1.json
  def show
  end

  # GET /venue_to_vendors/new
  def new
    @venue_to_vendor = VenueToVendor.new
  end

  # GET /venue_to_vendors/1/edit
  def edit
  end

  # POST /venue_to_vendors
  # POST /venue_to_vendors.json
  def create
    @venue_to_vendor = VenueToVendor.new(venue_to_vendor_params)

    respond_to do |format|
      if @venue_to_vendor.save
        format.html { redirect_to @venue_to_vendor, notice: 'Venue to vendor was successfully created.' }
        format.json { render :show, status: :created, location: @venue_to_vendor }
      else
        format.html { render :new }
        format.json { render json: @venue_to_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venue_to_vendors/1
  # PATCH/PUT /venue_to_vendors/1.json
  def update
    respond_to do |format|
      if @venue_to_vendor.update(venue_to_vendor_params)
        format.html { redirect_to @venue_to_vendor, notice: 'Venue to vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue_to_vendor }
      else
        format.html { render :edit }
        format.json { render json: @venue_to_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venue_to_vendors/1
  # DELETE /venue_to_vendors/1.json
  def destroy
    @venue_to_vendor.destroy
    respond_to do |format|
      format.html { redirect_to venue_to_vendors_url, notice: 'Venue to vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue_to_vendor
      @venue_to_vendor = VenueToVendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_to_vendor_params
      params.require(:venue_to_vendor).permit(:venue_id, :vendor_id, :vendor_type_id)
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    vendor_type = VendorType.find_by vendor_type: 'venue'
    vendor = Vendor.create( vendor_type: 'venue', vendor_type_id: vendor_type.id)
    @venue = Venue.new(name: venue_params[:name], vendor_id: vendor.id)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caterers_helper.rb
module CaterersHelper
end

app/helpers/florists_helper.rb
module FloristsHelper
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/vendor_dates_helper.rb
module VendorDatesHelper
end

app/helpers/vendor_types_helper.rb
module VendorTypesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/venue_to_vendors_helper.rb
module VenueToVendorsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venue_to_vendors/_form.html.erb
<%= form_for(@venue_to_vendor) do |f| %>
  <% if @venue_to_vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue_to_vendor.errors.count, "error") %> prohibited this venue_to_vendor from being saved:</h2>

      <ul>
      <% @venue_to_vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :venue_id %><br>
    <%= f.number_field :venue_id %>
  </div>
  <div class="field">
    <%= f.label :vendor_id %><br>
    <%= f.number_field :vendor_id %>
  </div>
  <div class="field">
    <%= f.label :vendor_type_id %><br>
    <%= f.number_field :vendor_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venue_to_vendors/edit.html.erb
<h1>Editing venue_to_vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue_to_vendor %> |
<%= link_to 'Back', venue_to_vendors_path %>

app/views/venue_to_vendors/index.html.erb
<h1>Listing venue_to_vendors</h1>

<table>
  <thead>
    <tr>
      <th>Venue</th>
      <th>Vendor</th>
      <th>Vendor type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venue_to_vendors.each do |venue_to_vendor| %>
      <tr>
        <td><%= venue_to_vendor.venue_id %></td>
        <td><%= venue_to_vendor.vendor_id %></td>
        <td><%= venue_to_vendor.vendor_type_id %></td>
        <td><%= link_to 'Show', venue_to_vendor %></td>
        <td><%= link_to 'Edit', edit_venue_to_vendor_path(venue_to_vendor) %></td>
        <td><%= link_to 'Destroy', venue_to_vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue to vendor', new_venue_to_vendor_path %>

app/views/venue_to_vendors/new.html.erb
<h1>New venue_to_vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', venue_to_vendors_path %>

app/views/venue_to_vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue:</strong>
  <%= @venue_to_vendor.venue_id %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @venue_to_vendor.vendor_id %>
</p>

<p>
  <strong>Vendor type:</strong>
  <%= @venue_to_vendor.vendor_type_id %>
</p>

<%= link_to 'Edit', edit_venue_to_vendor_path(@venue_to_vendor) %> |
<%= link_to 'Back', venue_to_vendors_path %>